#! /bin/bash
echo "Installing required packages"
echo "========== Starting Setup ==========" >> ./setup.log
echo "$(date)" >> ./setup.log

sudo dnf install -y python-setuptools git python-devel python-dnf libxml2-devel libxslt-devel redhat-rpm-config libselinux-python &>> ./setup.log

echo "Installing pip"
sudo easy_install pip &>> ./setup.log

echo "Installing Ansible"
sudo pip install -e git://github.com/ansible/ansible.git@v2.0.0.1-1#egg=ansible &>> ./setup.log

ansible_extra_vars=${@:1}
ansible-playbook setup.yaml -i HOSTS --ask-become-pass  --module-path ./ansible_modules -e "$ansible_extra_vars" 2>&1 | tee -a ./setup.log

echo "========== Finished Setup ==========" >> ./setup.log
echo "Set up complete, see ./setup.log for details"
