#! /bin/bash
echo "Installing required packages"
echo "========== Starting Setup ==========" >> ./setup.log
echo "$(date)" >> ./setup.log

dnf_packages=$(cat requirements/dnf | sed ':a;N;$!ba;s/\n/ /g')
sudo dnf install -y $dnf_packages &>> ./setup.log

echo "Installing Ansible"
sudo pip install -r requirements/pip &>> ./setup.log

echo "Installing Ansible Galaxy Requirements"
sudo ansible-galaxy install -r requirements/ansible.yaml &>> ./setup.log

ansible_extra_vars=${@:1}
ansible-playbook setup.yaml -i HOSTS --ask-become-pass  --module-path ./ansible_modules -e "$ansible_extra_vars" 2>&1 | tee -a ./setup.log

source ~/.bashrc

echo "========== Finished Setup ==========" >> ./setup.log
echo "Set up complete, see ./setup.log for details"
