- name: a playbook to setup my local machine with my basic customizations
  hosts: local
  connection: local
  become_method: sudo
  vars_prompt:
    - name: spideroak_password
      prompt: "Spideroak password"
      private: yes
  roles:
    - {role: dotfiles}
    - {role: beastop, when: "{{facter_fqdn.find('fedora.laptop') != -1}}"}
    - {role: lenovo, when: "{{facter_fqdn.find('fedora.lenovo') != -1}}"}
