- name: a playbook to setup my local machine with my basic customizations
  hosts: local
  connection: local
  become: yes
  become_method: sudo
  vars_prompt:
    - name: spideroak_password
      prompt: "Spideroak password"
      private: yes
  pre_tasks:

    - command: whoami
      register: reg_user_id
      become: no
    - debug: msg="User is {{reg_user_id.stdout}}"
      when: "{{debug}}"

    - command: uname -n 
      register: reg_device_name
    - debug: msg="Machine name is {{reg_device_name.stdout}}"
      when: "{{debug}}"

    - shell: getent passwd "{{reg_user_id.stdout}}" | cut -d ':' -f 5
      register: reg_user_name
    - debug: msg="User name is {{reg_user_name.stdout}}"
      when: "{{debug}}"

    - command: echo $HOME
      register: reg_user_home
      become: no
    - debug: msg="User home is {{reg_user_home.stdout}}"
      when: "{{debug}}"

    - command: which powerline
      register: reg_powerline_installed
    - debug: msg="powerline_installed + {{reg_powerline_installed.rc}}"
      when: "{{debug}}"

    - command: git passport warn=no
      ignore_errors: yes
      become: no
      register: reg_gitpassport_installed
    - debug: msg="gitpassport_installed + {{reg_gitpassport_installed.rc}}"
      when: "{{debug}}"
  roles:
    - {role: dotfiles}
    - {role: beastop, when: "{{reg_device_name.stdout.find('fedora.laptop') != -1 and install}}"}
