- name: a playbook to setup my local machine with my basic customizations
  hosts: local
  connection: local
  become_method: sudo
  roles:
    - {role: dotfiles}
    - {role: beastop, when: "{{ansible_fqdn.find('fedora.laptop') != -1}}"}
    - {role: lenovo, when: "{{ansible_fqdn.find('fedora.lenovo') != -1}}"}
