- debug: msg="gitpassport installed? = {{gitpassport_installed}}"
  when: debug

- name: ensure {{user_home}}/.gitpassport exists
  copy: src=roles/dotfiles/files/gitpassport dest="{{user_home}}/.gitpassport" owner={{user}}
  when: gitpassport_installed

- name: update {{user_home}}/.gitconfig for gitpassport
  when: gitpassport_installed
  blockinfile:
    dest: "{{user_home}}/.gitconfig"
    insertbefore: BOF
    marker: "# {mark} GITPASSPORT .GITCONFIG"
    block: |
      [alias]
          passport = !${HOME}/.git/hooks/bin/git-passport/git-passport.py
      [init]
          templatedir = ~/.git/templates
