- include_vars: "{{secrets_file}}"
  no_log: true

- name: install dropbox (and encryption deps)
  package: name={{item}} state=latest
  become: yes
  with_items:
    - dropbox
    - fuse-encfs.x86_64 
    - cryptkeeper.x86_64
    - expect

- name: create encfs unencrypted dir
  file: path={{dropbox_encfs_unencrypted_dir}} state=directory

- name: create encfs encrypted dir
  file: path={{dropbox_encfs_encrypted_dir}} state=directory

- name: copy encfs config
  copy: src=roles/common/files/encfs6.xml dest={{dropbox_encfs_encrypted_dir}}/.encfs6.xml

- name: unmount encfs if we need to
  command: fusermount -u {{dropbox_encfs_unencrypted_dir}}
  register: out
  failed_when: out.rc > 1

- name: mount unencrypted dir
  shell: echo {{dropbox_encfs_password}} | encfs -S {{dropbox_encfs_encrypted_dir}} {{dropbox_encfs_unencrypted_dir}}
  no_log: true
