- name: ensure {{user_home}}/.git/hooks/bin exists
  file: path="{{user_home}}/.git/hooks/bin" state=directory owner={{user}}

- name: clone gitpassport to {{user_home}}/.git/hooks/bin/git-passport
  git: repo=https://github.com/cfi/git-passport.git dest="{{user_home}}/.git/hooks/bin/git-passport" version=merged_regex_noremote 

- name: make sure {{user}} owns {{user_home}}/.git/hooks/bin/git-passport/
  command: chown -R {{user}} {{user_home}}/.git/hooks/bin/git-passport/ warn=no

- name: chmod execute {{user_home}}/.git/hooks/bin/git-passport/git-passport.py
  file: path="{{user_home}}/.git/hooks/bin/git-passport/git-passport.py" mode="u=rwx,g=rx,o=rx" state=file owner={{user}}

- name: ensure {{user_home}}/.git/hooks/pre-commit.d exists
  file: path="{{user_home}}/.git/hooks/pre-commit.d" state=directory owner={{user}}

- name: ensure {{user_home}}/.git/hooks/pre-commit.d/00-git-passport exists
  file: src="{{user_home}}/.git/hooks/bin/git-passport/git-passport.py" dest="{{user_home}}/.git/hooks/pre-commit.d/00-git-passport" state=link owner={{user}}

- name: ensure {{user_home}}/.git/templates/hooks exists
  file: path="{{user_home}}/.git/templates/hooks" state=directory owner={{user}}

- name: ensude {{user_home}}/.git/templates/hooks/pre-commit exists
  copy: src=roles/common/files/scripts/pre-commit dest="{{user_home}}/.git/templates/hooks/pre-commit" mode="u=rwx,g=rx,o=rx" owner={{user}}
