- name: install the latest version of pip
  package: name=python-pip state=latest

- name: install virtualenv
  pip:
    name: virtualenv
    state: latest

- name: update pip using pip
  pip:
    name: pip
    state: latest
