- name: install powerline
  package: name=powerline state=latest

- name: download powerline font symbols
  get_url:  url=https://github.com/Lokaltog/powerline/raw/develop/font/PowerlineSymbols.otf dest=/usr/share/fonts

- name: download powerline font symbols conf
  get_url: url=https://github.com/Lokaltog/powerline/raw/develop/font/10-powerline-symbols.conf dest=/etc/fonts/conf.d

- name: rebuild font cache
  command: fc-cache -vf

- name: ensure {{user_home}}/.config/powerline/themes/shell exists
  file: path="{{user_home}}/.config/powerline/themes/shell" state=directory  owner={{user}}

- name: copy powerline shell config to {{user_home}}/.config/powerline/themes/shell/default.json
  copy: src=roles/common/files/json/powerline_shell_config.json dest="{{user_home}}/.config/powerline/themes/shell/default.json" owner={{user}}

- name: install vim-enhanced
  package: name=vim-enhanced state=latest
