- name: install powerline
  pip: name=git+git://github.com/Lokaltog/powerline#egg=Powerline state=present extra_args="--user -I -b ."
  become: "{{user}}"

- name: create font directory
  file: path={{user_home}}/.fonts state=directory

- name: download powerline fonts
  get_url: url=https://github.com/Lokaltog/powerline/raw/develop/font/PowerlineSymbols.otf dest={{user_home}}/.fonts/

- name: create font config directory
  file: path={{user_home}}/.config/fontconfig/conf.d state=directory

- name: download powerline font conf
  get_url: url=https://github.com/Lokaltog/powerline/raw/develop/font/10-powerline-symbols.conf dest={{user_home}}/.config/fontconfig/conf.d/

- name: rebuild font cache
  shell: fc-cache -vf {{user_home}}/.fonts
