- name: install powerline
  package: name=powerline

- name: update bashrc
  blockinfile:
    dest: "{{user_home}}/.bashrc"
    block: |
      if [ -f `which powerline-daemon` ]; then
        powerline-daemon -q
        POWERLINE_BASH_CONTINUATION=1
        POWERLINE_BASH_SELECT=1
        . /usr/share/powerline/bash/powerline.sh
      fi

- name: configure powerline shell
  copy: src=roles/common/tasks/powerline_shell_config.json dest="{{user_home}}/.config/powerline/themes/shell/default.json
