- name: install powerline
  package: name=powerline state=latest

- name: ensure directory for user powerline themes exists
  file: path="{{user_home}}/.config/powerline/themes/shell" state=directory  owner={{user}}

- name: configure powerline shell
  copy: src=roles/common/files/powerline_shell_config.json dest="{{user_home}}/.config/powerline/themes/shell/default.json" owner={{user}}
