- name: create yum repo
  copy: src=roles/common/files/yum.repos.d/SpiderOakONE-stable.repo dest=/etc/yum.repos.d/SpiderOakONE-stable.repo

- name: install spideroak
  package: name=SpiderOak state=latest

- name: check for new user setup
  shell: sudo -u {{user}} SpiderOak --user-info
  register: result

- debug: msg="stdout {{result.stdout}}"
  when: "{{debug}}"

- name: generate spideroak setup file
  template: src=roles/common/files/spideroak.json dest=/dev/shm/spideroak.json
  when: result.stdout.find('New User Setup') != -1

- name: spideroak setup
  shell: sudo -u {{user}} SpiderOak --setup=/dev/shm/spideroak.json
  when: result.stdout.find('New User Setup') != -1

- name: remove spideroak setup file
  file: name=/dev/shm/spideroak.json state=absent
  when: result.stdout.find('New User Setup') != -1
