- name: install the latest version of python-pip
  package: name=python-pip state=latest
  become: yes

- name: install virtualenv
  become: yes
  pip:
    name: virtualenv
    state: latest

- name: update pip using pip
  become: yes
  pip:
    name: pip
    state: latest
