- name: install the latest version of python-pip
  package: name=python-pip state=latest

- name: install latest version of python3-pip
  package: name=python3-pip state=latest

- name: download pip/python3 fix
  get_url: url=https://bootstrap.pypa.io/get-pip.py dest=src/get-pip.py

- name: fix pip/python3
  command: python src/get-pip.py

- name: download easy_install/python3 fix
  get_url: url=https://bootstrap.pypa.io/ez_setup.py dest=src/ez_setup.py

- name: fix easy_install/python3
  command: python src/ez_setup.py

- name: install virtualenv
  pip:
    name: virtualenv
    state: latest

- name: update pip using pip
  pip:
    name: pip
    state: latest
