- name: ensure python3 is installed
  package: name={{item}} state=latest
  become: yes
  with_items:
    - python3
    - python3-devel

- name: setup python2 alternatives
  command: alternatives --install /usr/bin/python python /usr/bin/python2 1
  become: yes

- name: setup python3 alternatives
  command: alternatives --install /usr/bin/python python /usr/bin/python3 0
  become: yes
