- name: install libgestures dependencies
  package: name="{{item}}" state=latest
  with_items:
    - gcc-c++
    - jsoncpp
    - jsoncpp-devel

- name: clone libgetsures to ./src/libgestures
  git: repo=https://github.com/hugegreenbug/libgestures dest="./src/libgestures" update=no

- name: build libgestures
  command: make chdir=./src/libgestures

- name: install libgestures
  command: make install chdir=./src/libgestures

- name: clone libevdevc to ./src/libevdevc
  git: repo=https://github.com/hugegreenbug/libevdevc dest="./src/libevdevc" update=no

- name: build libevdevc
  command: make chdir=./src/libevdevc

- name: install libevdevc
  command: make install chdir=./src/libevdevc

- name: install xf86-input-cmt dependencies
  package: name="{{item}}" state=latest
  with_items:
    - xorg-x11-server-devel

- name: clone xf86-input-cmt to ./src/xf86-input-cmt
  git: repo=https://github.com/hugegreenbug/xf86-input-cmt dest=./src/xf86-input-cmt update=no

- name: configure xf86-input-cmt
  command: ./configure --prefix=/usr chdir=./src/xf86-input-cmt

- name: build xf86-input-cmt
  command: make chdir=./src/xf86-input-cmt/src

- name: install xf86-input-cmt
  command: make install chdir=./src/xf86-input-cmt/src

- name: backup synaptic touchpad configuration
  copy: src=/usr/share/X11/xorg.conf.d/50-synaptics.conf dest=/usr/share/X11/xorg.conf.d/50-synaptics.conf.backup force=no
  ignore_errors: yes

- name: delete synaptic touchpad configuration
  file: name=/usr/share/X11/xorg.conf.d/50-synaptics.conf state=absent

- name: copy 20-mouse.conf to /usr/share/X11/xorg.conf.d/20-mouse.conf
  copy: src=./src/xf86-input-cmt/xorg-conf/20-mouse.conf dest=/usr/share/X11/xorg.conf.d/20-mouse.conf

- name: copy 40-touchpad-cmt.conf to /usr/share/X11/xorg.conf.d/40-touchpad-cmt.conf
  copy: src=./src/xf86-input-cmt/xorg-conf/40-touchpad-cmt.conf dest=/usr/share/X11/xorg.conf.d/40-touchpad-cmt.conf

- name: copy 50-touchpad-cmt-elan.conf to /usr/share/X11/xorg.conf.d/50-touchpad-cmt-elan.conf
  copy: src=./src/xf86-input-cmt/xorg-conf/50-touchpad-cmt-elan.conf dest=/usr/share/X11/xorg.conf.d/50-touchpad-cmt-elan.conf

- name: enable tap input
  command: xinput --set-prop --type=int --format=8 "ETPS/2 Elantech Touchpad" "libinput Tapping Enabled" 1
